<a href="https://colab.research.google.com/github/shubha07m/Deep-learning-using-Python-CS5590/blob/master/neural_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


**Simple numpy based neural layer implementation**

In [ ]:
# (3 inputs) Input and First hidden layer #
input = np.random.randint(1,10,3)

weights1 = np.random.random((4,3))
bias1 = np.random.randint(1,10,4)
output1 = np.dot(input,weights1.T) + bias1

print(input.shape,weights1.shape, bias1.shape,output1.shape)
print(output1)

(3,) (4, 3) (4,) (4,)
[16.7130676  10.6537395   6.70299148 10.95292742]


In [ ]:
# Second hidden layer #
input = output1

weights2 = np.random.random((3,4))
bias2 = np.random.randint(1,10,3)
output2 = np.dot(input,weights2.T) + bias2

print(input.shape,weights2.shape, bias2.shape,output2.shape)
print(output2)

(4,) (3, 4) (3,) (3,)
[24.32749329 30.38837573 43.09490036]


In [ ]:
# Third hidden layer and output(two neuron) #
input = output2

weights3 = np.random.random((2,3))
bias3 = np.random.randint(1,10,2)
output3 = np.dot(input,weights3.T) + bias3

print(input.shape,weights3.shape, bias3.shape,output3.shape)
print(output3)

(3,) (2, 3) (2,) (2,)
[66.19565934 50.48285451]


In [ ]:
# ReLu activation based class selection #
np.max(output3,0)

27.11102172292486

**Class based neural layer implementation**

1.   Three layers
2.   Leaky ReLu activation



In [ ]:
class Layer:

  def __init__(self,n_input, n_neuron):
    self.weights = np.random.random((n_neuron, n_input))
    self.biases = np.random.randint(0,10,n_neuron)

  def forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights.T) + self.biases
    return self.output

# First layer: 3 input, 4 output
Layer1 = Layer(3,4)
output1 = Layer1.forward_pass([1,2,3])
print(output1)
print(output1.shape)

# Second layer: 4 input, 3 output
Layer2 = Layer(4,3)
output2 = Layer2.forward_pass(output1)
print(output2)
print(output2.shape)

# Third/final layer: 3 input, 1 output
Layer3 = Layer(3,1)
output3 = Layer3.forward_pass(output2)
print(output3)
print(output3.shape)

# Leaky ReLu
print(max(output3,40))

[10.38806936  6.12709075  8.13045249  4.07073969]
(4,)
[20.44521694 20.35329772 21.38738377]
(3,)
[27.11102172]
(1,)
40


***Neural layer implementation with batch based inputs***



In [116]:
# First layer: 3 (batch size = 5 (means 5 samples)) input, 4 output
# Each single batch output has 4 neuron outputs

Layer_new = Layer(3,4)
# batched_input = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11], [12,13,14]])
batched_input = np.random.random((5,3))
print(batched_input)
print(batched_input.shape)
batched_output = Layer_new.forward_pass(batched_input)
print(batched_output)
print(batched_output.shape)


# Second layer: 4 input, 3 output
Layer2 = Layer(4,3)
output2 = Layer2.forward_pass(batched_output)
print(output2)
print(output2.shape)

# Third/final layer: 3 input, 1 output
Layer3 = Layer(3,1)
output3 = Layer3.forward_pass(output2)
print(output3)
print(output3.shape)

[[0.61717494 0.49266667 0.8614784 ]
 [0.4469443  0.41021797 0.88250176]
 [0.31209335 0.9966212  0.15279145]
 [0.01953071 0.81035806 0.20137367]
 [0.56784981 0.00250876 0.59564533]]
(5, 3)
[[10.1735623   6.26890225  7.23712781  7.94355565]
 [ 9.96294317  6.09131224  7.14736034  7.8849159 ]
 [10.06647355  5.72424031  6.78919007  7.51795791]
 [ 9.67504285  5.41147207  6.62136653  7.41160092]
 [ 9.69003863  5.89823435  6.72357097  7.58163524]]
(5, 4)
[[16.89325045 23.03001584 18.9462154 ]
 [16.74980726 22.7776558  18.62952297]
 [16.47002159 22.46226787 18.01600894]
 [16.21078926 21.99369045 17.44027341]
 [16.46785396 22.14638996 17.93890082]]
(5, 3)
[[40.35838593]
 [39.96991702]
 [39.3789733 ]
 [38.66443346]
 [39.06425033]]
(5, 1)
