<a href="https://colab.research.google.com/github/shubha07m/Deep-learning-using-Python-CS5590/blob/master/neural_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np


**Simple numpy based neural layer implementation**

In [8]:
# (3 inputs) Input and First hidden layer #
input = np.random.randint(1,10,3)

weights1 = np.random.random((4,3))
bias1 = np.random.randint(1,10,4)
output1 = np.dot(input,weights1.T) + bias1

print(input.shape,weights1.shape, bias1.shape,output1.shape)
print(output1)

(3,) (4, 3) (4,) (4,)
[16.7130676  10.6537395   6.70299148 10.95292742]


In [9]:
# Second hidden layer #
input = output1

weights2 = np.random.random((3,4))
bias2 = np.random.randint(1,10,3)
output2 = np.dot(input,weights2.T) + bias2

print(input.shape,weights2.shape, bias2.shape,output2.shape)
print(output2)

(4,) (3, 4) (3,) (3,)
[24.32749329 30.38837573 43.09490036]


In [10]:
# Third hidden layer and output(two neuron) #
input = output2

weights3 = np.random.random((2,3))
bias3 = np.random.randint(1,10,2)
output3 = np.dot(input,weights3.T) + bias3

print(input.shape,weights3.shape, bias3.shape,output3.shape)
print(output3)

(3,) (2, 3) (2,) (2,)
[66.19565934 50.48285451]


In [44]:
# ReLu activation based class selection #
np.max(output3,0)

27.11102172292486

**Class based neural layer implementation**

1.   Three layers
2.   Leaky ReLu activation



In [43]:
class Layer:

  def __init__(self,n_input, n_neuron):
    self.weights = np.random.random((n_neuron, n_input))
    self.biases = np.random.randint(0,10,n_neuron)

  def forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights.T) + self.biases
    return self.output

# First layer: 3 input, 4 output
Layer1 = Layer(3,4)
output1 = Layer1.forward_pass([1,2,3])
print(output1)
print(output1.shape)

# Second layer: 4 input, 3 output
Layer2 = Layer(4,3)
output2 = Layer2.forward_pass(output1)
print(output2)
print(output2.shape)

# Third/final layer: 3 input, 1 output
Layer3 = Layer(3,1)
output3 = Layer3.forward_pass(output2)
print(output3)
print(output3.shape)

# Leaky ReLu
print(max(output3,40))

[10.38806936  6.12709075  8.13045249  4.07073969]
(4,)
[20.44521694 20.35329772 21.38738377]
(3,)
[27.11102172]
(1,)
40
